### ISSUE TITLE
Colorduino for scrolling text

### ISSUE THREAD

**Issue by Dancopy** [funnypolynomial/Chromaduino#1]
Greetings
What does this code do? I would like to use 2 or 3 Colorduino for scrolling text; Thank you

**Comment by funnypolynomial** [comment]
What the code does is act as a slave, driving the LED matrix with data provided over I2C from a master Arduino (refer to the readme or the Code tab).
It was written with a single matrix in mind, but I imagine you could address multiple slaves by giving each one a different I2C addresses.  See 
`#define WIRE_DEVICE_ADDRESS 0x05`
in Chromaduino.ino

Mark

**Comment by Dancopy** [comment]
Thanks for the reply, but I have some difficulties!
I would like to use 2 or 3 Colorduino to scroll a text message without needing the Master (Arduino); I use Arduino Duemilanove only to write code. So how should I proceed? Where do I write the message in the slave sketch? And if I use the sketch master to write the message, how do I?
Thanks++ Mark

Daniel Fernandes

**Comment by funnypolynomial** [comment]
My Chromaduino code implements a slave LED matrix.  It needs a Master to drive it. So if you don't want a master, you may need to use something else.  You could potentially hack a slave sketch to provide the scrolling text data to itself, and over I2C to another slave.
If you do want to use a master, have a look at the example.  Start by getting it going.

**Comment by Dancopy** [comment]
Thanks for the answer; sorry for my ignorance but, how do I write a text scrolling message in the Master and send it to the Slave? Thanks++

**Comment by funnypolynomial** [comment]
I will perhaps try to write some demo text scrolling code for you, depends if I have a spare LED matrix at home.
But before I start, what have you achieved?  
Have you downloaded the Chromaduino slave sketch onto a LED matrix board? 
If the matrix has power but no Master connected, it will show a colourful self-test demo after 5s, are you seeing the slave demo?
Have you downloaded the Master demo sketch to your Duemilanove and connected it to the Slave?
Are you seeing the Master's demo?

**Comment by Dancopy** [comment]
Yes, they both do their demonstration! Then I ask you,
1) What can be done with the master, besides the demonstration?
     If it is possible to do something, this is via serial monitor or in the code? (where?)
2) Can you, by kindness and kindness, make some text scrolling code with those beautiful fonts?
Once again, thank you very much for your kindness in answering me and your given attention.

**Comment by funnypolynomial** [comment]
The Master demo in this repository is just test code, it does very little.  
Please change your Master sketch at the bottom so that
```
void loop()
{
  DisplayBuffer();
  delay(1000);
  ...

```
becomes
```
void loop()
{
  DisplayBuffer();
  delay(100); // change 1000 to 100!
  ...

```
and verify that the demo runs **faster**.
You could make other changes to the master yourself, including scrolling text...
Which "beautiful fonts" are you referring to?
What brand of 8x8 RGB LED matrix are you using?

**Comment by funnypolynomial** [comment]
Were you not able to get this guy's Instructable to work [http://www.instructables.com/id/Colorduino-Scrolling-Text/](url)?
I got an initial scrolling text demo going with 1 matrix last night, will probably try two (joined together) tonight.

**Comment by funnypolynomial** [comment]
Note also that I did a bit of tidying up to the repository, including fixing Chromo instead of Chroma typos :-)

**Comment by Dancopy** [comment]
It worked yes, but he used a '5x8 glcdfont' from the Adafruit library (very lean); I tried to adapt to an external 8x8 font (fuller) but I could not.
I'll wait for your text scrolling code for 2 or more Colorduino; Thank you

**Comment by Dancopy** [comment]
Thank you; I'll look

**Comment by funnypolynomial** [comment]
My sample will include a small simple font.  Changing to use a different one should be straight-forward.  
Can you provide a link to the font you're interested in?

**Comment by Dancopy** [comment]
Like this one here: https://github.com/Electromondo-Coding/ColorduinoScrollerLibrary/blob/master/font.c

**Comment by Dancopy** [comment]
Like this one here: https://github.com/Electromondo-Coding/ColorduinoScrollerLibrary/blob/master/font.c

**Comment by Dancopy** [comment]
Hi Mark!
I sent you through 'github.com' the font style you asked me but, the correct font I am sending you attached; is in HCColorDuino> HCColorDuino.h.
In the Examples folder there are some demos, such as Hello_World; who knows you can adapt the sketch to several Colorduino?
Thank you

Daniel
________________________________
De: Mark Wilson <notifications@github.com>
Enviado: quinta-feira, 12 de julho de 2018 01:03
Para: funnypolynomial/Chromaduino
Cc: Dancopy; Author
Assunto: Re: [funnypolynomial/Chromaduino] Colorduino for scrolling text (#1)


My sample will include a small simple font. Changing to use a different one should be straight-forward.
Can you provide a link to the font you're interested in?

**Comment by funnypolynomial** [comment]
Was there supposed to be a link or attachment in your previous message about HCColorDuino?

I got the two-matrix scrolling demo going last night.  Noticed two things:

- difficult to match the colour balance of the two units I was using, the differences between them are mos noticeable when side-by-side.  White is a bad choice.
- a little slower than I'd like, but then the slave wasn't designed to handle animations

I intend to enhance the slave to have a faster way of updating.  
I will probably also change the I2C address, since I think what I'm using now (0x05) is probably non-standard

**Comment by Dancopy** [comment]
I had sent you an attachment via email!

**Comment by funnypolynomial** [comment]
I can't see any attachment on any messages in github or the copies it emails me.  How did you send it?

**Comment by Dancopy** [comment]
Hi mark!
I am sending you again the font style you asked me to.
The correct font that I'm sending to you is in "HCColorDuino> HCColorDuino.h."
Also, in the Examples folder there are some demos, such as Hello_World; who knows you can adapt the sketch to several Colorduino?
Thanks again
[HCColorDuino.zip](https://github.com/funnypolynomial/Chromaduino/files/2195958/HCColorDuino.zip)

**Comment by funnypolynomial** [comment]
OK, got it this time.

**Comment by funnypolynomial** [comment]
I've updated the repository.  You should download the **new** Chromaduino.ino (the slave sketch) and upload it to your **first** LED matrix.  Then you should **modify** the sketch to change the WIRE_DEVICE_ADDRESS to be **0x71** and upload that to your **second** LED matrix.  Connect the second matrix to the first.  Connect the first matrix to your master Uno.  Then upload the attached sketch to the master Uno. 
[ChromaduinoTextScroller.zip](https://github.com/funnypolynomial/Chromaduino/files/2212144/ChromaduinoTextScroller.zip)
You should see scrolling text.

**Comment by Dancopy** [comment]
Thank you very much, I will test but I have two more questions:
1) How many matrices can I connect together? I know I should change the WIRE_DEVICE_ADDRESS to be 0x71, 0x72, 0x73, ..... etc.
2) After saving the sketch 'Chromaduino.ino' on all slaves, and loading the sketch 'ChromaduinoMaster' in the master Uno, can I disconnect the Arduino and connect only all the Colorduino together? Thanks again

**Comment by funnypolynomial** [comment]
1. Yes, in theory you can extend to 3 or more.  Program the extra slave matrices with increasing address, update the arrays and the define etc.  You may encounter difficulty powering too many off the +5V pin on the Master (which is 500mA max I think)

2. No, the Master is what is controlling the scrolling text, you can't remove it.  The point of Chromaduino is that it is simple and dumb and needs to be told what to display.

**Comment by Dancopy** [comment]
Hi Mark! I'm afraid I'm bothering you!
Sorry for my ignorance but how do I use the Master to send text message or other characters / shapes? I mean, where do I write this in the sketch?
Or is it via serial monitor? Thanks++

**Comment by funnypolynomial** [comment]
So you have it working?  You're seeing "Hello, world!" and "ATMEL Inside" scrolling?
It's a simple matter to search the sketch for "Hello"  and you'll find the relevant code, a function called `void UpdateText()`.
It's a demonstration, so it just alternates between the two strings, you will need to change the sketch to scroll the text you want.  Not using the serial monitor, although you could do that if you wanted.

**Comment by Dancopy** [comment]
Sorry, now I'm a little confused!
There are now 4 files: Chromaduino, ChromaduinoMaster, ChromaduinoScrollDemoMaster, from github.com plus this one you sent me attached: ChromaduinoTextScroller;
So I write the 'Chromaduino' in the two slaves and which one do I write in the Master? The ChromaduinoTextScroller?
And the other two? 'ChromaduinoMaster' and 'ChromaduinoScrollDemoMaster' what are they?
Thanks again++

**Comment by funnypolynomial** [comment]
The first three files are part of this repository.  Chromaduino is the slave. ChromaduinoMaster is the original master demo (just changes colours). ChromaduioScrollDemoMaster is a new master which demonstrates text scrolling with a simple self-contained (upper-case only) font.

ChromaduinoTextScroller is not part of the repository.  It's based on the demo but I changed it for you to use the HCColorDuino font, as you requested.
So yes, Chromaduino is uploaded to the two LED matrices (with different i2C address) and ChromaduinoTextScroller goes onto your Uno, connected to them.  Then you can change ChromaduinoTextScroller to scroll the text you want.

**Comment by Dancopy** [comment]
Hi Mark!
Worked perfectly! Many thanks for the beautiful and excellent work! You deserve my compliments!
Thanks for mentioning my nickname "Dancopy" in the opening texts of your sketch.
Of course I will also mention your Name when sharing and if I happen to modify your code for some reason.
Later, I want to try to adapt the code to modify the messages through Bluetooth; You certainly have thought of that.
But, one question already arises: Is it possible to determine a different color for each text? For example, "Hello, world!" in Blue and "ATMEL Inside" in Red.
Once again, thank you and God bless you, my friend!

**Comment by funnypolynomial** [comment]
Good to hear.

Of course you can change the colour, it's up to you.  I would imagine moving the
`static bool Hello = true;`
line **out** of `void UpdateText()` to just **before** `void SendDisplay(int matrix)`
Then changing 
`  WriteData(matrix, 0, 0, 255);  // blue foreground`
to
```
if (Hello)
  WriteData(matrix, 0, 0, 255);  // blue foreground
else
  WriteData(matrix, 255, 0, 0);  // red foreground

```
would probably do it.

**Comment by Dancopy** [comment]
Hi Mark! 100% - you hit the fly!
I tried to change the background color by changing "data[0] = B00000010;" but nothing has changed. Another thing: the text, instead of moving smoothly, moves with "little jumps", do you understand me?
One more thing, and I will not bother you any more: For me to create another sentence (message), I add another "else" after strcpy(markStr, " ");
   Hello =! Hello; on void UpdateText ( )?

Again, thank you very much+++

**Comment by funnypolynomial** [comment]
No problem, this discussion has resulted in improvements to the sketch (fast command, 0x11).
Before I answer your questions, please attach a photo of your setup, with some text showing on the LED matrices.

**Comment by Dancopy** [comment]
I do not understand what you mean
"attach a photo of your setup, with some text showing on the LED matrices." Would it be like this attached image?
![image](https://user-images.githubusercontent.com/37884487/43334794-627365b8-91a4-11e8-8c47-4dfefc5895f8.png)
I would like to add here 2 more text message lines with different colors. Thank you

**Comment by funnypolynomial** [comment]
I would not call that a "photo".  I mean a **photo** of your **hardware**.  Like this:
![leds](https://user-images.githubusercontent.com/5882685/43352899-ac8af446-927f-11e8-9ade-6165242ef0d3.jpg)

**Comment by Dancopy** [comment]
Sorry, Mark! See if you can understand with this Photo. The matrices are rolling perfectly; I just want to add more lines of text with different colors;
Hugs from Brazil,
Daniel
![colorduino](https://user-images.githubusercontent.com/37884487/43370243-e9155046-9351-11e8-9d60-07ce30227828.jpg)

**Comment by funnypolynomial** [comment]
OK, thanks for that.  Re your earlier questions:
I have no idea why you tried changing `data[0]`, my suggested code changes did not mention that line at all. That line changes the background colour and the update behaviours.  Refer to the documentation.

How could the text to not "jump" from one column of LEDs to the next?  You can change the scrolling speed by changing the `#define DELAY (150) `line.

Since a `bool` is either true or false, it's hard to make it control three different messages to display.  You could use an `int `instead.

**Comment by Dancopy** [comment]
OK friend! You've done enough for me!
On data[0], for my ignorance on the subject, I found that if I changed 'B00000010' to another number, the background color in the array would change; But I was mistaken!
If you accept, when more doubts arise, I ask you!
PS. I would love to program in Colorduino, so would you have any good books that explain this coding issue? 
A big hug from Brazil and, again, my thanks!
Daniel Fernandes

**Comment by funnypolynomial** [comment]
Do you know how to change the program to get what you want?  

If not, I can easily do it and provide you a new sketch which displays 4 strings, in different colours.

**Comment by Dancopy** [comment]
Hi Mark! I know it's easy for you, so if you do not mind doing it, I'll be very grateful and besides, I'm learning from you!

**Comment by funnypolynomial** [comment]
Version 2 attached:
[ChromaduinoTextScrollerV2.zip](https://github.com/funnypolynomial/Chromaduino/files/2244055/ChromaduinoTextScrollerV2.zip)
Scrolls 4 strings (see `marqueeStrs` array) each a different colour (see `marqueeColours` array)

- Note that you can flip the whole display around by commenting out `#define DISPLAY_ROTATED`
- Note also that you may need to adjust the colour balances for your individual matrices, see the `matrixBalances` array.  You can see on my photo the blue is brighter on the left one.  The real test is trying to get a good white (255, 255, 255)

**Comment by Dancopy** [comment]
Greetings Mark! It worked perfectly friend!
About adjusting the balance, I do not care much about it; I'd really like to learn how to do these codes to, for example, merge into the text, for example, a blinking heart but, I find that very difficult.
What I know is very basic, like, just working with leds, etc.
Anyway, once again, I want to thank you very much for your cordiality and willingness to help me.
Daniel

**Comment by funnypolynomial** [comment]
Well, play around.  
If I wanted a blinking heart in the text I would do something along these lines:

- character 3 ('\x03') is a heart in the HCColorDuino font, so edit a string to be like "I \x03 Arduino".
- in `UpdateDisplay()`, if the character is a '\x03', show it (the heart) half the time, otherwise blank (' '). use `if (marqueeCol % 2)`

**Comment by funnypolynomial** [comment]
Ah, no that font **doesn't** have a heart symbol.  See attached V3.  
[ChromaduinoTextScrollerV3.zip](https://github.com/funnypolynomial/Chromaduino/files/2248316/ChromaduinoTextScrollerV3.zip)
I've modified the ~ character to be a heart and added blinking code.  Make
`#define HEART_BLINK_RATE (2)`
a larger number (eg 4) to blink slower.

**Comment by Dancopy** [comment]
Sensational Mark!  You're an expert on the subject, buddy!
Mark, 1) how can I know what is what in the HCColorDuino.h font?
For example:
{0x00,0x00,0x00,0x4F, 0x4F, 0x00,0x00,0x00}, (what does it mean?)
{0x00,0x07,0x07,0x00,0x00,0x07,0x07,0x00}, (what does it mean?)
etc... That is, it does not define whether it is A, B, C, d, e, f, .....
2) What program do you use to edit these fonts?
3) Which book would you recommend?
My sincere thanks+++++

**Comment by funnypolynomial** [comment]
Those lines define a single character in the font by defining which "pixels are on.  They are 8 bytes (each 8 bits).  They are entered in hexadecimal (base 16). You can use a calculator to convert them. 0x4F is 79 decimal.  However, it's easier to do it in binary, 0x4F is 01001111, 0x07 is 00000111.  Arduino has some defines which let you use binary directly, that would be **B**01001111 and B00000111.  I defined my heart shape using this method (I didn't use a "program").  If you spread the 8 values across multiple lines it's easier to see the pattern, tilt you head to the right :-):
```
  {B00001100,
   B00011110,
   B00111110,
   B01111100,
   B01111100,
   B00111110,
   B00011110,
   B00001100} // ~ is a heart
```
the examples you list are
```
  {B00000000,
   B00000000,
   B00000000,
   B01001111,
   B01001111,
   B00000000,
   B00000000,
   B00000000},
  {B00000000,
   B00000111,
   B00000111,
   B00000000,
   B00000000,
   B00000111,
   B00000111,
   B00000000}

```
which look like '!' and '"', the first two after " " in the font.
The HCColorDuino font defines characters from ' ' to '~' (or heart).  Refer to an ASCII chart to find a particular one (count the lines). [](https://www.asciitable.com/).
There are plenty of books out there, I don't have one to recommend.  It's probably easier to find examples and tutorials on-line

**Comment by Dancopy** [comment]
Hi Mark! I would stay here again! I'm learning a lot from you!
But, I suspect you must be a "new kid" and I'm a 50-year old "old man"! I understood well what you explained to me about the characters, but I have a problem: since my language is Portuguese (Brazil), there are some characters that are accentuated, such as: á, ã, é, ó, etc, that do not have in the library of characters, so it can be added or these characters have to be created?
Mark, I have one more challenge for you: to make half a character of one color and the other half of another color, like here: https://www.youtube.com/watch?v=dPAFEAyB9fA (at 0:30)
Of course, if you want to do this; I know you can do it!
Once again, thank you and a good weekend to you.

**Comment by funnypolynomial** [comment]
Actually, I'm older that you.  
You could add the accented characters to the font, either at the beginning (before space, ' ') or at the end, after '~' (heart).  You would need to change `font_GetCell()` to adjust for that.  You would need to enter the accented characters into you strings with \xNN hex escape sequences.

You could do the top-half/bottom-half colour thing too, but it would be a bit of work. 
`void SendDisplay(int matrix)` would need to do the top half then the bottom half.  For bottom half, Data[0] would need to be B00000000 so the first half wasn't over-written.

I'll leave that all for you to do, it's the best way to learn.

**Comment by Dancopy** [comment]
So we're two boys (lol)!
OK! I did not quite understand the accentuated sources;
I'll try, if I can, I'll let you know.
Thank you so much for everything!

**Comment by funnypolynomial** [comment]
If you only need a few accented characters for your specific message, you could just hack the existing characters in the same way that I hacked '~' to be a heart.  For example, modify the ':', ';', '<', '=', '>' and '?' font definitions to look like  'á', 'ã', 'é', 'ó' etc.  If you wanted to show "Familiá" you would use "Famili:" in the sketch.  Simple and gets the job done.

**Comment by Dancopy** [comment]
Many thanks for the tip, I'll do it!
Now I'm going to break my head with the other party!
Hi Mark! Are you from North America?
Do you work with electronics or use it as a hobby?
Hugs from Brazil,
Daniel

**Comment by funnypolynomial** [comment]
Electronics is just a hobby, but programming is my day job.
I'm in New Zealand.

**Comment by Dancopy** [comment]
You know Mark, I get confused about these codes because, for example, you wrote this code for that purpose, so, someone else writes another code for the same purpose, does not it?
For example, you told me that to do the characters in two colors (top and bottom), this has to do with 'void SendDisplay (int matrix)' and Data [0], and these functions do not exist in the code (youtube) that I sent him as an example.
But ... living and learning! And I've learned a lot from you and, until I'm 100, I learn more (lol)!

**Comment by Dancopy** [comment]
Ah! New Zealand. Must be a beautiful country!

**Comment by projjwaldhar** [comment]
Hey Mark!
Greetings from India.
Excellent job on the Chromaduino I2C Master/Slave I2C communication thing, I must say!
However, I needed to use it for a slightly different purpose.
I wonder if there is anyway to get the Slave Chromaduino display something (in this case, an emoji face) from the Master Arduino? The Master Arduino would pick up digital/analog inputs and accordingly tell the Slave Chromaduino to display pre-defined emoji faces. Your concept of  Slave Chromaduinos being dumb & needed to be told what to display works perfectly for me, only I just needed to figure out how to get it to display what I want. I tried using the standard Colorduino library but to no avail, it was all so messed up.

Thank you so much!
Projjwal

**Comment by funnypolynomial** [comment]
Hi Projjwal,
The master Arduino telling the slave Chromaduino what to display is exactly what this is designed to do.  So you should be able to achieve what you want.  Although an 8x8 matrix is going to be a very chunky emoji.  Perhaps you are planning a 2x2 grid of matrices, or more? Do you have the demo running?

**Comment by Dancopy** [comment]
Hi Mark! Are you all right?
I'm waiting for a few more Colorduino pieces to make a longer array; I hope you have not bothered with me! A big hug

**Comment by projjwaldhar** [comment]
Yup, I'm going for the retro effect here (chunky as you put it) with 1 Chromaduino.
What's bugging me is that I can't figure out how to get the Slave Chromaduino to display an emoji (or any custom character, like if I describe an 8x8 array of RGB values for the individual LEDs)
Yes, I have the demo running, and I even modified it to change the foreground colour and the custom text banner.
If it's not too much to ask for, can you please send me a sample code of it displaying any custom character (defined as 8x8 array of RGB values for the individual LEDs) ? I know I'm asking you to go out of your way to do me a favour here but after 16 days of tearing out my hair over this, I think I have hit a dead end here. Thank you so much for replying to my comment.

**Comment by funnypolynomial** [comment]
Sure, I'll whip something up soon

**Comment by funnypolynomial** [comment]
Projjwal, 
Please find attached, a sketch which just cycles through some "emoji".

- I've used a simple colour palette; one byte per LED
- comment-out the `#define ROTATE_DISPLAY` line to turn the displayed shapes 180deg

[ChromaduinoMasterEmoji.zip](https://github.com/funnypolynomial/Chromaduino/files/2307771/ChromaduinoMasterEmoji.zip)

Mark

**Comment by projjwaldhar** [comment]
Wow! Frankly, I'm amazed at your helpfulness! I couldn't thank you enough for this.
Right now I'm on a break for a week, but I'll try it out as soon as I get back, can't wait to test it out. Had a look at the code and I understood all of it (thanks to your well placed and helpful comments)
So I think it won't take me more than a few minutes to tweak it and get it do what I want.
Thanks a lot again for going out of your way and taking your time to help me out, man!
I really appreciate it. :)
Cheers!

**Comment by funnypolynomial** [comment]
You're welcome, I hope it works out, let me know.
