### ISSUE TITLE
How to connect master with slave? Is there any schematic?

### ISSUE THREAD

**Issue by jakubprzybylski** [funnypolynomial/Chromaduino#2]
I've uploaded master code to master Arduino Uno, slave code to Colorduino (Colorduino demo works like a charm), but the master does nothing (changing delay value inside loop in master's code has no effect).

I've connected Colorduino SCL to A4 pin of Arduino Uno (master). Colorduino SDA to A5 pin of Uno (master). GND to GND.

Am I missing something here? Code looks good, I must have gotten something wrong with wiring it up.

Is this schematic also relevant for Uno? https://hackster.imgix.net/uploads/attachments/238281/p036VjisJZuDMSAGmUTB.png (omitting every element besides Nano and LED matrix here)

**Comment by jakubprzybylski** [comment]
Nevermind, the schematics posted above is wrong.

SDA should go to A4 pin. SCL should go to A5 pin. And now it works! :)

**Comment by funnypolynomial** [comment]
Thanks, I've corrected this on the hackster.io project page
